services:
  backend:
    container_name: i-help-backend-dev
    hostname: backend
    image: i-help-backend:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - /app/node_modules
    ports:
      - ${CONTAINER_PORT}:${SERVER_PORT}
    env_file:
      - .env.dev
    restart: on-failure
    depends_on:
      - mongodb
    environment:
      WAIT_HOSTS: mongodb:${DATABASE_PORT}
      WAIT_LOGGER_LEVEL: info

  mongodb:
    container_name: i-help-db-dev
    image: mongo:7.0.5
    restart: on-failure
    ports:
      - "27017:27017"
    volumes:
      - ihelp:/data/db
      - ./seed/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./seed/ya-pomogau-db.users.json:/docker-entrypoint-initdb.d/ya-pomogau-db.users.json:ro
      - ./seed/ya-pomogau-db.contacts.json:/docker-entrypoint-initdb.d/ya-pomogau-db.contacts.json:ro
      - ./seed/ya-pomogau-db.categories.json:/docker-entrypoint-initdb.d/ya-pomogau-db.categories.json:ro

networks:
  default:
    driver: bridge

volumes:
  ihelp:
